"""Add events_etag to person

Revision ID: 6c03835e01a0
Revises: b23bc9ebff08
Create Date: 2026-09-02 02:40:57.453183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c03835e01a0'
down_revision: Union[str, Sequence[str], None] = 'b23bc9ebff08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('events_etag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'events_etag')
    # ### end Alembic commands ###
