"""Add OAuth columns to Owner

Revision ID: b23bc9ebff08
Revises: 65d516186ae5
Create Date: 2026-09-02 02:33:34.995128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23bc9ebff08'
down_revision: Union[str, Sequence[str], None] = '65d516186ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('github_id', sa.BigInteger(), nullable=True))
    op.add_column('owners', sa.Column('encrypted_access_token', sa.Text(), nullable=True))
    op.add_column('owners', sa.Column('token_scopes', sa.String(), nullable=True))
    op.add_column('owners', sa.Column('is_builder', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('owners', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('owners', sa.Column('person_id', sa.Integer(), nullable=True))
    op.add_column('owners', sa.Column('highlights_acked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('owners', sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('owners', sa.Column('collect_in_progress_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'owners', ['github_id'])
    op.create_foreign_key(None, 'owners', 'people', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owners', type_='foreignkey')
    op.drop_constraint(None, 'owners', type_='unique')
    op.drop_column('owners', 'collect_in_progress_at')
    op.drop_column('owners', 'last_collected_at')
    op.drop_column('owners', 'highlights_acked_at')
    op.drop_column('owners', 'person_id')
    op.drop_column('owners', 'last_login_at')
    op.drop_column('owners', 'is_builder')
    op.drop_column('owners', 'token_scopes')
    op.drop_column('owners', 'encrypted_access_token')
    op.drop_column('owners', 'github_id')
    # ### end Alembic commands ###
