HIGHLIGHTS_LIMIT = 3
HIGH_SIGNIFICANCE_MIN = 10

RISING_MIN_PEOPLE = 3
RISING_MULTIPLIER = 2.0
NEW_IN_NETWORK_MIN_PEOPLE = 2
DECLINING_PRIOR_MIN = 3
PRIOR_WINDOW_DAYS = 28

CLOSE_QUIET_MAX_SLOTS = 1
COLLECT_STALE_SECONDS = 600  # crash recovery for collect_in_progress_at

NARRATE_LLM_MIN_SCORE = 8
